### ISSUE TITLE
where is example-pr-checks.yaml?

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-ci#108]
As contributor,

I would like to see example of PR check file mentioned in README.

See: https://github.com/AICoE/aicoe-ci/blob/master/docs/how-to-contribute.md#how-to-contribute

**Comment by harshad16** [comment]
Thanks for the kind question
The example pr yaml is here: https://github.com/AICoE/aicoe-ci/blob/master/tasks/example-pr-checks.yaml
we will update the docs.
