### ISSUE TITLE
Automate Sesheta's acceptance of contributor invites [meteor]  

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/aicoe-ci#126]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I have to wait an unknown amount of time for a human to accept my contributor invite to Sesheta and start using the AICoE-CI. 

**Describe the solution you'd like**
Sesheta automatically accepts contributor invites. 

**Describe alternatives you've considered**
None 

**Additional context**
This is relevant to making the user experience of the [elyra tutorial](https://github.com/AICoE/elyra-aidevsecops-tutorial) with meteor smoother.

**Comment by harshad16** [comment]
we will work on it .
The procedure we would follow is:
- user would need to open an issue follow this template: https://github.com/AICoE/aicoe-ci/issues/new?assignees=goern%2Charshad16&labels=area%2Fcyborgs%2Cbot%2Csig%2Fcyborgs&template=request_sesheta.yaml&title=Help+with+Sesheta+invite
- then add automation to resolve them with bots.
wdyt ?
