### ISSUE TITLE
create tekton bundle

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#127]
**Is your feature request related to a problem? Please describe.**
create a build/delivery pipeline to quay to deliver a tekton bundle

**Describe the solution you'd like**
https://tekton.dev/docs/pipelines/tekton-bundle-contracts/

**Describe alternatives you've considered**
tbd

**Additional context**
turn this into a reusable capability for ODH, Meteor, https://issues.redhat.com/projects/ODH/issues/ODH-417?filter=allopenissues

/kind feature
/priority important-soon
/assign @harshad16 @tumido 
/label needs-triage

**Comment by tumido** [comment]
Cross-linking https://github.com/AICoE/meteor/issues/90#issuecomment-899591771
