### ISSUE TITLE
Help with Sesheta invite

### ISSUE THREAD

**Issue by suppathak** [AICoE/aicoe-ci#132]
### GitHub Repo

https://github.com/suppathak/elyra-aidevsecops-tutorial

**Comment by goern** [comment]
I (logged in to GitHub as sesheta) actually dont see an invite to this repo. 

/assign @suppathak 
/triage needs-information

**Comment by goern** [comment]
done.
/close

@pacospace @harshad16 one needs to log into GitHub as @sesheta  and go to https://github.com/suppathak/elyra-aidevsecops-tutorial/invitations to actually see the invite :/
