### ISSUE TITLE
Add Tekton Chains to AICoE-CI deployment on op1st

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#150]
chains is pretty easy to add:

`kubectl apply -f https://storage.googleapis.com/tekton-releases/chains/previous/v0.5.0/release.yaml`

_Originally posted by @lukehinds in https://github.com/AICoE/summit-2021-octo-keynote/issues/7#issuecomment-948775599_

/kind feature
/priority important-soon
/assign harshad16
/assign screeley44
/kind demo

**Comment by codificat** [comment]
/remove-lifecycle stale

Tekton Chains is deployed on Operate First (https://github.com/operate-first/support/issues/438).
The missing piece is the ability to push signatures to quay.io (see https://github.com/AICoE/summit-2021-octo-keynote/issues/28)
