### ISSUE TITLE
Help with Sesheta invite

### ISSUE THREAD

**Issue by negillett** [AICoE/aicoe-ci#160]
### GitHub Repo

https://github.com/os-climate/physrisk

**Comment by goern** [comment]
Hey Nathan, thanks for reaching out. I cant see the repo, is it private?

**Comment by harshad16** [comment]
unfortunately, the aicoe-ci doesn't work on the private repo.
what use case are you looking for ?

**Comment by negillett** [comment]
Okay. Thank you!

Yeah, we were directed to integrate it for CI and checks. I think the idea was to have all of os-climate org repos plugged in but maybe this is suppose to happen later, once our repos are made public.

I've mentioned this issue on our end to further the discussion.
It's probably safe to close it now as it'll be some time before our golive.

**Comment by harshad16** [comment]
Sounds good
Also if you would like to test the aicoe-ci bot, users can install them.
Having sesheta as a collaborator is not a necessity it is just good to have, they still function the same without sesheta as a collaborator. 
Closing this issue for now.
please reach out to us, we are always happy to help.
