### ISSUE TITLE
Create a task for thoth-github-action testing 

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-ci#177]
**Is your feature request related to a problem? Please describe.**
With respect to: https://github.com/thoth-station/thoth-github-action/issues/19
we would like to have a pipeline that would act on PR in [thoth-github-action](https://github.com/thoth-station/thoth-github-action) repo and create a PR in the Test repo with the change of commit.

- [ ] Create a custom task for : Test-PR
   - [ ] Create a separate [binding](https://github.com/AICoE/aicoe-ci/blob/master/trigger/git-pr-binding.yaml) and gather params like: commit hash, repo details
   - [ ]  create steps:
      - [ ]  To patch the commit hash in test repo
      - [ ]  To create PR
   - [ ]  If we want to do certain action, lets create a test.yaml in thoth-github action repo PR, grab that action from test.yaml in a step and execute it before creating a PR.

**Comment by mayaCostantini** [comment]
Close as addressed by https://github.com/thoth-station/thoth-github-action/pull/57 with local tests as GitHub Actions and https://github.com/AICoE/aicoe-ci/pull/178 for the aicoe-ci task.
