### ISSUE TITLE
build from main

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#186]
**Is your feature request related to a problem? Please describe.**
For a project in early development, it would be very handy to build container images on each push to master. Having a high frequency of tags being created and deployed after each PR is merged seems to be an un-productive overload

**Describe the solution you'd like**
1. trigger a build-deploy on push to main branch
2. cancel any existing build-deploy of an older commit

**Describe alternatives you've considered**
Build/Deploy from PR, with a subsequent tag-release after PR merged @durandom and rational why this is not that good?

**Additional context**
simply fully building on each push to main might overload the cluster...

/assign @Gregory-Pereira 
/assign @harshad16 
/priority critical-urgent

**Comment by Gregory-Pereira** [comment]
Development on this feature was halted almost immediately as the `Thoth-Station` project was moved to hiatus. This issue will be closed, and may be re-opened when development resumes.
