### ISSUE TITLE
(3) create Tekton CD pipeline for solver images [NOKR]

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#21]
As Thoth-CI
I want to run a Tekton Pipeline
so that I build all solver container images
and so that I push them to quay as `v<git-tag>`

**Goal**
Have a tekton pipeline run on each tag of git repository

**References**
- https://quay.io/repository/thoth-station/solver-....
- https://github.com/thoth-station/solver

**Acceptance Criteria**

- [x] new `v0.6.0-dev` release on push to master branch of git
- [ ] review how integration with build-wathcer works

**Comment by harshad16** [comment]
Use the feature of custom pipeline to build and push quay for solver images.
It is enabled in solver and is functioning.
