### ISSUE TITLE
No color output if copying to pr comment

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#30]
**Is your feature request related to a problem? Please describe.**
We should not use any colored output if we copy it to a pr comment, GitHub does not support that (or in s different way)

**Comment by harshad16** [comment]
The feature for pr commenting needs more refactoring, will include the suggestion request of no including the colour.

**Comment by harshad16** [comment]
This was updated in the coala checks https://github.com/AICoE/aicoe-ci/commit/98d7ef596a74d5ad738add2b321f1a612eeab053#diff-9137472e08eddd2b5b4a0eade1b83253R49, 
however, the coala check have been taken over by pre-commit checks.
closing this issue.
