### ISSUE TITLE
create Tekton CD pipeline for solver images

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#36]
As Thoth-CI
I want to run a Tekton Pipeline
so that I build all solver container images
and so that I push them to quay as v<git-tag>

**Goal**
Have a tekton pipeline run on each tag of git repository

**Acceptance Criteria**

- [ ] review how integration with build-wathcer works

**References**
https://quay.io/repository/thoth-station/solver-...
https://github.com/thoth-station/solver

**Comment by harshad16** [comment]
The solver images are updated to be built with the custom-build pipeline of aicoe-ci.
The build-watcher is another completed which listen to the build config and image stream of openshift, as this tekton pipeline uses pipeline task concept, build-watcher would not be able to benefit from the image built in these environments. 
This following commit https://github.com/thoth-station/solver/commit/1a0f63fcf8cd3c7d4858b570ee860e6cb1136716 task care of this in solver repository.
