### ISSUE TITLE
ODH App Stack CI pipeline [13pt]

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#37]
As ... 
I want to run a tektoncd pipeline,
so that I can continuously deliver ODH container images to quay.

**Story Points:** 13
**Key-Result:** NOKR

**Goal**
build all jupyterhub app stack (notebook) images via a tektoncd pipeline

**Acceptance Criteria**

- [x] jupyterhub image is published automatically on git tag event
- [x] jupyterhub-img is published automatically on git tag event
- [x] notebook-images are published automatically on git tag event
- [x] tektoncd pipeline is hosted on PSI
- [ ] tektoncd pipeline artifacts are published on github

**References**

* https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/overlays/build/jupyterhub-buildconfig.yaml#L12
* https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/overlays/build/jupyterhub-dh-buildconfig.yaml#L11
* https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images
* https://github.com/opendatahub-io/odh-manifests/issues/37
* https://gitlab.com/opendatahub/opendatahub-operator/-/issues/218
* https://github.com/kubeflow/kubeflow/issues/4789
* https://github.com/opendatahub-io/odh-manifests/issues/43

**Comment by vpavlin** [comment]
@goern Is there any progress? We are ready to start verifying the images and switching to them

**Comment by harshad16** [comment]
The pipeline is helping out in building odh images 
- jupyterhub base images
- other odh images like airflow, etc 
- also enabled to build the operator

all the images are on the quay in different odh orgs.
please let me know if anything is missing, i would be happy to get aicoe-ci work for anything missing.

**Comment by harshad16** [comment]
Most of the jupyterhub image is build and published with help of aicoe-ci 
This issue seems to be completed.
