### ISSUE TITLE
experiment with a instance of prow.

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-ci#39]
Get a [prow](https://github.com/kubernetes/test-infra/tree/master/prow#) installation to serve the pull request interaction for aicoe.
Ideally would like an instance of [prow](https://github.com/kubernetes/test-infra/tree/master/prow#) for whole aicoe GitHub projects.

Init-step:
- [ ]  Start with deployment on a quick lab cluster for a sample of the thoth-station repository.
- [ ]  Extend it for other repositories of thoth-station.
- [ ]  Extend it for whole aicoe repositories.
- [ ] Integrate Prow so it can run Tekton Pipelines as a Job

References:
- [config file](https://github.com/thoth-station/test-infra/tree/master/thoth-station)
- [prow deployment](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md)
- [prow openshift deployment](https://github.com/charlesakalugwu/openshift-prow-tackle)

**Comment by harshad16** [comment]
https://github.com/opendatahub-io/odh-manifests/issues/64

**Comment by goern** [comment]
seeAlso https://github.com/thoth-station/srcops-testing/pull/240

**Comment by harshad16** [comment]
This following pull request https://github.com/thoth-station/thoth-application/pull/544 is the continuous work regarding this issue

**Comment by harshad16** [comment]
we have moved on with have the prow and pipeline in separate deployment.
