### ISSUE TITLE
pipelinerun should set github pr status.state to 'pending'

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#4]
**Is your feature request related to a problem? Please describe.**
If a pipeline is run for the second time on the same PR, the status of the first run is still shown until the pipeline resets the status, this is confusing.

**Describe the solution you'd like**
each pipeline run shall set the status to pending as one of the very first tasks

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by harshad16** [comment]
This would handle this issue: https://github.com/thoth-station/aicoe-ci/commit/622957dbbb35ccf841033c56593c8c049cfef428
Keeping this open will refactor the code more.

**Comment by goern** [comment]
![Bildschirmfoto 2020-05-29 um 08 46 43](https://user-images.githubusercontent.com/260331/83229956-3204fa80-a189-11ea-91b0-72afb0293cb5.png)
❤️

**Comment by harshad16** [comment]
closing this issue as this is already happening on all pipeline runs.
