### ISSUE TITLE
aicoe-ci should be able to run tox/pytest as required by micropipenv

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#40]
**Is your feature request related to a problem? Please describe.**
https://github.com/thoth-station/micropipenv/issues/101

**Describe the solution you'd like**
AICoE CI Pipeline should run tox/pytest, in the best case we can reuse tasks from some catalog.

**Comment by harshad16** [comment]
The tox test is created and available in aicoe-ci.
will check on its availability for micropipenv and update this issue sooner.

**Comment by harshad16** [comment]
We had the https://github.com/AICoE/aicoe-ci/blob/master/tasks/tox-checks.yaml task for this.
However, the requirement for running the experiments for different python version, caused the issue in the multiple instance running.
Travis CI test are already being used, we can experiment with the prow ci test. As that better inclines towards this purpose.
closing this issue.
