### ISSUE TITLE
Python 3.8 for checks

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#41]
**Is your feature request related to a problem? Please describe.**
We should start using Py38 for checks run by tekton.

https://github.com/aicoe-aiops/sync-pipelines/pull/6
https://github.com/aicoe-aiops/sync-pipelines/pull/7

**Comment by goern** [comment]
argh... sorry for all the spam :/

**Comment by tumido** [comment]
@goern do you have any timeframe for this? The clutter in the sync pipelines repo is quite annoying (because every check essentially fails). What should I do to disable these PR checks from sesheta on our repo in the meantime?

**Comment by harshad16** [comment]
I m really sorry @goern  and @tumido 
this one really missed out of my eyes. 

> @goern do you have any timeframe for this?
will start the work right away.

> What should I do to disable these PR checks from sesheta on our repo in the meantime?
i will open a pr which a support configuration file. @tumido

**Comment by tumido** [comment]
Hi @harshad16 is there any PR to follow on this? I know you already have it in some branch, since you've spilled this secret to me... :smile: I would like to finally rely on AICoE-CI on my PRs. :slightly_smiling_face:

**Comment by harshad16** [comment]
Hi @tumido ,yes.
i m testing it on my fork and work send in the pr soon.
https://github.com/harshad16/sync-pipelines/pull/2
