### ISSUE TITLE
send release notification to devops channel

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#42]
**Is your feature request related to a problem? Please describe.**
It might be handy to receive a notification if a new tag release has been pushed to quay or pypi by a tekton pipelinerun

**Comment by harshad16** [comment]
Thanks for the feature requests, the following step would be implemented for this feature. 
Step for creating the task to serve the feature:
- [ ] create a task that sends out a notification on other task completion. 
   -  [ ] use the **result** method to confirm the completion of other tasks.
- [ ] identify the pipelines in which these tasks should be included too.

**Comment by goern** [comment]
Shall we use https://github.com/nolar/kopf to create a tiny controller, that watches for `taskruns.tekton.dev` object changes, specifically the ones labels with `tekton.dev/pipelineTask: tag-publish-pypi-run`, then checks for `status.condition` if there is one condition that has `type: success` and `status: true`. if that is found, use some credentials from ENV to send out a chat notification.

with this architecture, we make the notification part of the platform/aicoe-ci rather than a pipeline.
