### ISSUE TITLE
Provide ability to tag the new release with a custom tag

### ISSUE THREAD

**Issue by vpavlin** [AICoE/aicoe-ci#47]
**Is your feature request related to a problem? Please describe.**
The pipeline only provides explicit tags, but sometimes it would be useful to be able to have the new build also tagged with a custom tag (e.g. `latest` or `released`) 

e.g. in "multi-stage" builds, where you have multiple images depending on each other - like `s2i-scipy-notebook -> s2i-minimal-notebook` - I would like to be able to use tag `released` for the base image of `s2i-scipy-notebook` so that I am sure I always build on top of the latest git release (but at the same time I may not want to use `latest` which maybe  points to `master`)

**Describe the solution you'd like**
Provide an option in `.aicoe-ci.yaml` which allows user to define a custom tag (e.g. `custom-tag: released` or `custom-tag: latest`). 

If this is not `null` then the pipeline will build image based on new git release (e.g. `v0.0.z`) and also tag with the given tag

This can also be used to make sure the `latest` tag points to the latest release, but since `latest` is kind of messy in the container image world, it should not be assumed this "latest" tag name has always the value `latest` hence `custom-tag`.

**Describe alternatives you've considered**
Current alternative (AFAIK) is to manually tag the image after release, which is error prone (user can easily forget to do it) and, well, manual

**Comment by harshad16** [comment]
we are making this option of having an extra tag optional, it can be configured via the aicoe-ci configuration file as suggested. 
By adding:
```
build:
    custom-tag: latest
```

**Comment by harshad16** [comment]
This feature is now available in running instance of aicoe-ci.
Thanks for an opening the issue with the feature request.
