### ISSUE TITLE
Provide built image URL in comment from sesheta

### ISSUE THREAD

**Issue by vpavlin** [AICoE/aicoe-ci#48]
**Is your feature request related to a problem? Please describe.**
Currently Sesheta will add a comment stating:

> Successfully built and delivered the image.

**Describe the solution you'd like**
I would like the comment to contain also the url of the built image, ideally in a form of clickable link:

> Successfully built and delivered the image  [quay.io/thoth-station/s2i-minimal-notebook:v0.0.5](https://quay.io/thoth-station/s2i-minimal-notebook:v0.0.5)

(source: `Successfully built and delivered the image  [quay.io/thoth-station/s2i-minimal-notebook:v0.0.5](https://quay.io/thoth-station/s2i-minimal-notebook:v0.0.5)`)

Since Quay will automatically redirect the image URL to console URL, so user can easily get to a list of tags and see that everything is as expected

**Describe alternatives you've considered**

**Additional context**

**Comment by harshad16** [comment]
This feature is now available in the running instance of aicoe-ci. 
The following commit added this feature to the pipeline https://github.com/AICoE/aicoe-ci/commit/9643f36c73a891b5ef0bb4b77acab2e0750ee05c

Thanks for opening the feature issue.
Please keep helping us make a better application.
