### ISSUE TITLE
migrate to ocp-prod [3pt]

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#58]
OCP cluster is on 4.3 with OpenShift Pipeline Operator, ArgoCD should be reconfigured to deploy to that cluster, rather than `thoth01`

/kind feature
/priority critical-urgent
/assign @harshad16

**Comment by harshad16** [comment]
The aicoe-ci is now migrated to ocp cluster manually, 
- opened few pull-request in aicoe-cd for argocd help.
- opened a [ticket](https://redhat.service-now.com/help?id=rh_ticket&is_new_order=true&table=sc_request&sys_id=2778d3f21b0f1c50c57c3224cc4bcb9a) with psi to also provide tekton dashboard for easy usability.

**Comment by harshad16** [comment]
with the merge of the pull request https://github.com/AICoE/aicoe-cd/pull/108, the aicoe-ci is now successfully executing in ocp cluster.
Argocd application https://argocd-server-aicoe-argocd.apps.ocp.prod.psi.redhat.com/applications/aicoe-ci
