### ISSUE TITLE
Provide automated PRs that would update repo from the original template

### ISSUE THREAD

**Issue by tumido** [AICoE/aicoe-ci#63]
**Is your feature request related to a problem? Please describe.**
The amount of repositories derived from https://github.com/aicoe-aiops/project-template (and probably https://github.com/thoth-station/template-project ) grows... It would be nice if we can use AICoE-CI to propagate the template changes and update the children repositories, so they all are in sync with the template and we don't maintain "multiple versions" of the same standard.

**Describe the solution you'd like**
Fetch and rebase children repository when the template repo's HEAD is updated. To get the parent template repository from Github REST API use `Accept: application/vnd.github.baptiste-preview+json` header:

```
$ curl -s -H "Accept: application/vnd.github.baptiste-preview+json" https://api.github.com/repos/aicoe-aiops/sync-pipelines

{
  "id": 276931347,
  "node_id": "MDEwOlJlcG9zaXRvcnkyNzY5MzEzNDc=",
  "name": "sync-pipelines",
  "full_name": "aicoe-aiops/sync-pipelines",
   ...
  "template_repository": {
    "id": 207786768,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDc3ODY3Njg=",
    "name": "template-project",
    "full_name": "thoth-station/template-project",
    "private": false,
    ...
  }
  ...
}
```

**Describe alternatives you've considered**
Each repo maintainer would have to keep track of the template updates manually. That may cause troubles when the template updates introduces changes later used in other automation which relies on these changes - like when the repo is being build into a s2i image, or in a case when we would like to propagate changes to the repo layout (like https://github.com/AICoE/internal-data-hub/issues/9 ), etc.

**Additional context**
Merging from unrelated history (template may have unrelated history) may be dangerous, but I think automating these updates may be beneficial in a long run. Also auto approval of the PRs in children repos should not be expected here.

What do you think ? @goern  @durandom @harshad16

**Comment by goern** [comment]
@saisankargochhayat @fridex This sounds like a feature for Kebechet?! A new manager?

/kind feature

**Comment by fridex** [comment]
> @saisankargochhayat @fridex This sounds like a feature for Kebechet?! A new manager?

+1 on my side

**Comment by goern** [comment]
@saisankargochhayat could you please take this and turn it into a kebechet feature? thx!!

**Comment by harshad16** [comment]
This feature is moved to Thoth-station Kebechet Bot.
thanks for the feature request.
It can be monitored here: https://github.com/thoth-station/kebechet/issues/540
