### ISSUE TITLE
Tekton dashboards outage

### ISSUE THREAD

**Issue by tumido** [AICoE/aicoe-ci#67]
**Describe the bug**
I'd like to have the Tekton Dashboards (publicly) accessible, currently I can't access them, even though I'm on VPN. Is this an outage?

**To Reproduce**
1. Go to https://github.com/AICoE/idh-manifests/pull/12
2. Scroll to PR checks
3. See failing check and click the "Details"
4. [Site can't be reached](http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/aicoe-ci/pipelineruns/aicoe-pipelinerun-6w84h)

**Expected behavior**
View the check results

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/94553534-f1adaa00-0258-11eb-9ed9-804cd79f22ca.png)

**Comment by harshad16** [comment]
@tumido , we have recently moved around the aicoe-ci system to new deployment.
new pull-request test runs can be seen in new dashboard.
`https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/#/namespaces/aicoe-infra-prod/pipelineruns/`

**Comment by tumido** [comment]
Ah, nice.. yeah, all the recent runs point to the right location. Thank you.
