### ISSUE TITLE
Push images to the latest tag on release

### ISSUE THREAD

**Issue by tumido** [AICoE/aicoe-ci#68]
**Is your feature request related to a problem? Please describe.**
We want our deployments to auto-pick up the newly built and released images. AI-CoE CI can successfully release, build and publish the image on quay. The image is properly tagged as the released version. We would like the CI to tag the quay image as the `latest` as well 

**Describe the solution you'd like**
Tag the same image as was released as `vX.Y.Z` as `latest` as well.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tumido** [comment]
cc @harshad16 @goern

**Comment by harshad16** [comment]
This issue is in work in progress

**Comment by harshad16** [comment]
we are making this option of having a extra tag optional , it can be configured via the aicoe-ci configuration file. 
By adding:
```
build:
    custom-tag: latest
```

as other teams would like to push the tag image to some other named tag like `master`, `released` etc.
following the suggestion in: https://github.com/AICoE/aicoe-ci/issues/47

**Comment by tumido** [comment]
Does this custom tag replace the original version tag or is this an additional tag for the same image?

**Comment by tumido** [comment]
Never mind.. I've found it in the PR. It's an additional tag for the same image. Good stuff @harshad16 ! :+1:

**Comment by harshad16** [comment]
yes, exactly its an additional tag.
will close this issue with documentation updates with all details.
however, we can start using the feature as it already in the production.

**Comment by harshad16** [comment]
This feature is now available with this PR: https://github.com/AICoE/aicoe-ci/pull/70
thanks for the feature request.
