### ISSUE TITLE
Auto update pre-commit hooks

### ISSUE THREAD

**Issue by tumido** [AICoE/aicoe-ci#74]
**Is your feature request related to a problem? Please describe.**
Keeping things up to date is always a struggle. AICoE-CI can help with python dependencies and such. I think it would be nice to be able to keep `pre-commit` hooks up-to-date as well.

**Describe the solution you'd like**
AICoE-CI would create automated PRs if `pre-commit` hook is updatable. This can be checked/performed via `pre-commit autoupdate`. Running this command results in updated `.pre-commit-config.yaml` which can be submitted as the PR.

For example `pre-commit autoupdate` in [thoth-station/template-project](https://github.com/thoth-station/template-project) results in:

```sh
$ pre-commit autoupdate
Updating git://github.com/Lucas-C/pre-commit-hooks ... updating v1.1.1 -> v1.1.9.
Updating git://github.com/pre-commit/pre-commit-hooks ... updating v2.0.0 -> v3.3.0.
Updating git://github.com/pycqa/pydocstyle.git ... updating 4.0.1 -> 5.1.1.
Updating https://github.com/pre-commit/pre-commit-hooks ... updating v2.3.0 -> v3.3.0.
Updating https://github.com/pre-commit/mirrors-mypy ... updating v0.770 -> v0.790.
Updating https://github.com/psf/black ... updating 19.10b0 -> 20.8b1.
Updating https://gitlab.com/PyCQA/flake8 ... updating 3.7.8 -> 3.8.4.

$ git status --short
 M .pre-commit-config.yaml
```

**Describe alternatives you've considered**
Manual updates

**Additional context**
Pre-commit hook updates are not that fast pacing and are not part of the critical chain of the actual codebase, so priority of this is kinda low.

**Comment by harshad16** [comment]
Thanks for the feature requests, the following step would be implemented for this feature. 
Step for creating the task to serve the feature:
- [ ] create a task which updates pre-commit hooks and send out a pull request.

It has to be determined if it this should be triggered on all events or on specified ones.

**Comment by goern** [comment]
Shouldn't this be a Kebechet manager? Kebechet is our cyborg junior developer, it should do all the mundane updating tasks...
