### ISSUE TITLE
Have aicoe-ci task for verifying kustomization changes

### ISSUE THREAD

**Issue by anishasthana** [AICoE/aicoe-ci#81]
**Is your feature request related to a problem? Please describe.**

Kustomization builds often fail due to small changes being made in already existing PRs that result in the build failing.

**Describe the solution you'd like**
An aicoe-ci task for running a kustomize build on incoming PRs would greatly improve the quality of life for our teams.

**Comment by anishasthana** [comment]
cc @HumairAK

**Comment by HumairAK** [comment]
This would be EXTREMELY useful. There is one caveat, we use ksops and you'll need to be able to securely store our decryption keys for the test to reference from.

**Comment by anishasthana** [comment]
from a usage perspective, both Internal Data Hub and Operate-First would get a lot of mileage out of it.

**Comment by HumairAK** [comment]
@harshad16

**Comment by harshad16** [comment]
Thanks for opening the issue. Would plan on this. 
Do share suggestions.

**Comment by goern** [comment]
please have a look at https://github.com/thoth-station/thoth-application/commit/6c7b847d642b9949591ded6241f0cc703c9e4d6f
