### ISSUE TITLE
Add mypy task

### ISSUE THREAD

**Issue by KPostOffice** [AICoE/aicoe-ci#94]
**Is your feature request related to a problem? Please describe.**
I want to be able to run mypy seperately from pre-commit so that I can used installed dependencies for cross package type hints.

**Describe the solution you'd like**
New task based off of `pytest` image which runs mypy

**Comment by goern** [comment]
/kind feature

@KPostOffice please have a look at https://github.com/thoth-station/adviser/pull/1694#issuecomment-784190994 does this what you though about?

**Comment by KPostOffice** [comment]
Yes, it needs the flag `--ignore-missing-imports` and being able to pass a specific set of files/directories.  Running `mypy` on test dir will almost always fail.

**Comment by goern** [comment]
cool, could you send a PR please? :)

**Comment by goern** [comment]
@KPostOffice is there any subsequent task we need to do to fix https://prow.operate-first.cloud/log?job=thoth-mypy-py38&id=1367055350460583936 ?

/assign @KPostOffice
