### ISSUE TITLE
Using GitHub night mode you cannot see the architecture

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-ci#96]
**Describe the bug**
Using GitHub night mode you cannot see the architecture

**To Reproduce**
1. Move to Github night mode.
2. Have a look at the architecture

**Expected behavior**
User can read architecture

**Screenshots**
![Screenshot from 2021-03-05 20-00-17](https://user-images.githubusercontent.com/27498679/110161409-98d8d380-7ded-11eb-8da8-f853c5ea96f6.png)

**Additional context**

**Comment by harshad16** [comment]
Thank you for pointing. 
Hope the fix is good.
