### ISSUE TITLE
create `tekton.operate-first.cloud` and serve the tekton dashboard via that url

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#98]
SSIA

- [x] configure DNS
- [ ] create letsencrypt certs
- [ ] create route via manifest file

/kind feature
/sig user-experience
/assign @harshad16

**Comment by goern** [comment]
DNS is set up: `dig +trace -t ANY aicoe-ci.operate-first.cloud`

**Comment by tumido** [comment]
Related to https://github.com/operate-first/apps/issues/192

**Comment by harshad16** [comment]
This would be used in `tekton.operate-first.cloud` place of `aicoe-ci.operate-first.cloud`
@goern i don't have permission to get the certs for this domain as these from different services.

**Comment by harshad16** [comment]
This commit https://github.com/AICoE/aicoe-ci/commit/c610e76592a9543f0d779e061c5aa2b0b8f95a3e introudces the custom route for the tekton-dashboard.

**Comment by goern** [comment]
the URL is available, thanks!!

/close
