### ISSUE TITLE
build a Ceph Disk Failure Prediction Service deliverable

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#99]
**Feature**
As a CephAdmin,
I want to run a disk prediction failure service
I want to use a systemd unit file to run the containerized services
I want to run it on CoreOS
so that a Ceph deployment can use it via REST
and so that the Ceph community can take over maintenance

As a Ceph Developer,
I want to use AICoE-CI and enable Thoth services,
so that the container image contains always the most secure software stack
and so that Ceph community adopts it

/sig pipelines
/sig cyborgs
/kind feature
/assign @harshad16 
/assign @chauhankaranraj

**Comment by harshad16** [comment]
Closing this issue due to inactiveness
please re-open the issue, if this is still valid.
